# _krevsky_Spring

###
# @name getAllVideos
GET http://localhost:8080/video

###
# @name addVideo
POST http://localhost:8080/video
Content-Type: application/json

{
  "name": "title_3",
  "url": "url3",
  "duration": "300"
}

###
# @name getVideoByName
GET http://localhost:8080/video/search/findByName?title=title_1

###
# @name getVideoByDurationLessThan
GET http://localhost:8080/video/search/findByDurationLessThan?duration=201